### ISSUE TITLE
iOS: Migrate to build with SPM + Bazel

### ISSUE THREAD

**Issue by hborawski** [player-ui/player#156]
Migrate away from CocoaPods as a package manager, and build through SPM

We will still publish to CocoaPods but we do not need to build and resolve our dependencies through it, as it complicates usage of Bazel

**Comment by hborawski** [comment]
on https://github.com/player-ui/player/tree/bazel-6

```sh
bazel build //:PlayerUI_Pod
```

will build a SPM compatible zip

zip contents still needs to be published to a separate repo so the JS files will be present in the git location

**Comment by fangmobile** [comment]
any update for swift support?

**Comment by KetanReddy** [comment]
Closing because core work is done, issue to document consumption is #495
