### ISSUE TITLE
Android: Render label for collection reference asset

### ISSUE THREAD

**Issue by hborawski** [player-ui/player#160]
The core type for the [collection reference asset](https://github.com/player-ui/player/blob/main/plugins/reference-assets/core/src/assets/collection/types.ts#L5) defines a `label` as well as `values`. Currently the Android CollectionAsset [only renders values](https://github.com/player-ui/player/blob/main/plugins/reference-assets/android/src/main/java/com/intuit/player/android/reference/assets/collection/Collection.kt#L28-L30).

Update this asset to render the label to match the [React reference asset](https://github.com/player-ui/player/blob/main/plugins/reference-assets/react/src/assets/collection/Collection.tsx#L9-L13)

**Comment by Yian17** [comment]
@hborawski could you please assign this to me?
