### ISSUE TITLE
React: Add footer to info reference asset

### ISSUE THREAD

**Issue by hborawski** [player-ui/player#161]
To better model some real world scenarios, the `info` asset should be able to render content below the `actions`.

Add a `footer` to the [info asset](https://github.com/player-ui/player/blob/main/plugins/reference-assets/core/src/assets/info/types.ts) and render it in the [react reference asset](https://github.com/player-ui/player/blob/main/plugins/reference-assets/react/src/assets/info/Info.tsx)

**Comment by GOYALAYUSH782** [comment]
@hborawski I did not understand the requirement? Can u explain by visuals maybe? I can enhance for react.

**Comment by hborawski** [comment]
The `info` asset is used to represent a whole page, many applications render footer content consistently across screens for common links, like contact information.

This page itself is an example of that:

![Screenshot 2023-10-06 at 8 42 03 AM](https://github.com/player-ui/player/assets/1325154/0cd8a0e4-7e4d-4605-91ab-75a847fce1ee)

So the ask with this enhancement is to enable the `info` asset to render content below the `actions`, you can view the current `info` asset here: https://player-ui.github.io/latest/storybook-demo/?path=/story/reference-assets-info--info

**Comment by parthit** [comment]
Can you assign me this task? I can take this on

**Comment by vg300** [comment]
Hi @hborawski, is this issue still open? I would like to take it up.
