### ISSUE TITLE
iOS: Add footer to info reference asset

### ISSUE THREAD

**Issue by hborawski** [player-ui/player#162]
Depends on #161 

To better model some real world scenarios, the `info` asset should be able to render content below the `actions`.

Render the `footer` for  the [SwiftUI reference asset](https://github.com/player-ui/player/blob/main/ios/packages/reference-assets/Sources/SwiftUI/InfoAsset.swift)

**Comment by kurultai** [comment]
Hi, can I work on this issue? (I'm Vivian Zhu from Intuit)
