### ISSUE TITLE
Android: Add footer to info reference asset

### ISSUE THREAD

**Issue by hborawski** [player-ui/player#163]
Depends on #161 

To better model some real world scenarios, the `info` asset should be able to render content below the `actions`.

Render the `footer` for  the [Android reference asset](https://github.com/player-ui/player/blob/main/plugins/reference-assets/android/src/main/java/com/intuit/player/android/reference/assets/info/Info.kt)

**Comment by sugarmanz** [comment]
Closing as was done in #398
