### ISSUE TITLE
Core: Transform Info asset actions

### ISSUE THREAD

**Issue by hborawski** [player-ui/player#164]
The reference [react info asset](https://github.com/player-ui/player/blob/main/plugins/reference-assets/react/src/assets/info/Info.tsx#L20-L37) segments actions based on their value, to display side by side in larger viewports.

To leverage this for tablet views in iOS and Android, we should move this segmentation logic to a [transform](https://player-ui.github.io/latest/assets/transforms). And remove the react specific code to leverage the transformed data.

**Comment by manansharma18** [comment]
Hey, I am from FS Canada and I can take a look a look at this one.

**Comment by manansharma18** [comment]
https://github.com/player-ui/player/pull/191
