### ISSUE TITLE
iOS: Render note for Input reference asset

### ISSUE THREAD

**Issue by hborawski** [player-ui/player#167]
The core [input asset](https://github.com/player-ui/player/blob/main/plugins/reference-assets/core/src/assets/input/types.ts#L20) also declares a `note` field to display under the input.

Render the `note` field in the [iOS reference input asset](https://github.com/player-ui/player/blob/main/ios/packages/reference-assets/Sources/SwiftUI/InputAsset.swift) with the same [styling as react](https://player-ui.github.io/latest/storybook-demo/?path=/story/reference-assets-input--input)

**Comment by aarianasingh** [comment]
Hi, can I work on this?

**Comment by aarianasingh** [comment]
Hi, can I work on this issue?
