### ISSUE TITLE
Android: Render note for Input reference asset

### ISSUE THREAD

**Issue by hborawski** [player-ui/player#168]
The core [input asset](https://github.com/player-ui/player/blob/main/plugins/reference-assets/core/src/assets/input/types.ts#L20) also declares a `note` field to display under the input.

Render the `note` field in the [Android reference input asset](https://github.com/player-ui/player/blob/main/plugins/reference-assets/android/src/main/java/com/intuit/player/android/reference/assets/input/Input.kt) with the same [styling as react](https://player-ui.github.io/latest/storybook-demo/?path=/story/reference-assets-input--input)

**Comment by TieuKhang** [comment]
Hi @hborawski , can I work on this issue?
