### ISSUE TITLE
Core: Transform reference action asset role

### ISSUE THREAD

**Issue by hborawski** [player-ui/player#169]
The reference [react action asset]() currently renders a `<` icon when the value of the action indicates that the user would go backwards in the flow. Rather than have assets on each platform implement this check, we can move it into the [transform](https://player-ui.github.io/latest/assets/transforms) and expose a generic property in the [action metadata](https://github.com/player-ui/player/blob/main/plugins/reference-assets/core/src/assets/action/types.ts#L24) to make the coupling between icon and value looser.

- Move logic for determining `isBackAction` into the [action transform](https://github.com/player-ui/player/blob/main/plugins/reference-assets/core/src/assets/action/transform.ts) and populate a `role` property in the `metaData` when applicable.

- Update the [react asset](https://github.com/player-ui/player/blob/main/plugins/reference-assets/react/src/assets/action/Action.tsx#L22) to use `metaData.role` instead of checking the value directly.

**Comment by abhisheksrivastava177** [comment]
Hi @hborawski 
I am interested in working this feature of player. Can you assign me this and it's references ?

**Comment by manansharma18** [comment]
Hey @mercillo , I can have a crack at it. @abhisheksrivastava177 do you have a fix for this issue?

**Comment by manansharma18** [comment]
Working on it now

**Comment by manansharma18** [comment]
Hey @hborawski and @mercillo , a quick question. If we add a ref property in the asset  then going ahead all the FRF can specify that if they need an icon or not. For the already implemented back button, we need to make sure they keep showing the icon. Is that what the transform would be used for?  Is it to make sure the changes are backward compatible with older back buttons.

**Comment by mercillo** [comment]
I think previously, we're only checking to see if the value contains `Prev` to see if its a back button. 
but if the value contains Prev we can add the metadata in the transform

metaData: { "role": "back}

**Comment by hborawski** [comment]
Yes this is to consolidate existing logic, not to add arbitrary icons to the `action` asset

**Comment by manansharma18** [comment]
https://github.com/player-ui/player/pull/211
