### ISSUE TITLE
React: New Reference Asset - Choice

### ISSUE THREAD

**Issue by hborawski** [player-ui/player#182]
Depends on #181 

Consuming the new core `choice`, provide a [rendering implementation in React](https://github.com/player-ui/player/tree/main/plugins/reference-assets/react/src/assets) that displays the asset as a radio buttons. 

- Render the `label` of each choice entry next to the radio button

- Render the `title` of the `choice` above the radio buttons

- Render `validation` information below the radio buttons

**Comment by chowdhuryqaizar** [comment]
Taking this issue

**Comment by AditiChikkali** [comment]
can i take this issue?
