### ISSUE TITLE
Android: Race condition causes previous view to hydrate again

### ISSUE THREAD

**Issue by A1shK** [player-ui/player#403]
**Describe the bug**
[These](https://github.com/player-ui/player/pull/343) changes exposed a race condition in player.  Sometimes when we update an input and skip validations when continuing to the next screen, the previous screen gets rendered again in navigation. 

**To Reproduce**
Replace default.json with this [gist](https://gist.github.com/A1shK/c4d8aacedb726cace758374ab7da501b) and run the android demo app. Type in something in the input field and click continue. You might have to try this a few times and maybe navigate to another flow and come back for the race condition to happen. But you will know it happens when you click "Continue" and you are still one the first screen with the input. 

[race-condition.webm](https://github.com/player-ui/player/assets/129784222/ca1b0caf-3a2b-474e-ae90-109bbcde38f5)

 These are the logs from the last navigation in the above video:
 
![image](https://github.com/player-ui/player/assets/129784222/e9b1abe5-0a50-4bd3-a11f-5ef717f19af1)

You can see that `tmp.required` was updated and we transitioned from `VIEW_Start to VIEW_Navigated using Continue`. But then you can see another log showing that view with `ID KitchenSink-Skip-Validation took 69ms to render and display on screen`. 

**Expected behavior**

The view with ID `KitchenSink-Page-Navigated` should have rendered. 

**Environment:**

Tried this on both bazel 5 and bazel-6-android branches. 

- OS: Android

**Additional context**

**Comment by A1shK** [comment]
I am going to spend today looking into this but would love any pointers or ideas from someone more familiar with this space

**Comment by brocollie08** [comment]
fixed for consumers using `PlayerFragment` in base PlayerFragment https://github.com/player-ui/player/pull/471/files#diff-0df63a2b957538299107a6e9baa6fcc8131aa13e43a135efbc602e0160c7b094R182
