### ISSUE TITLE
Error thrown while generating error message for missing asset-type

### ISSUE THREAD

**Issue by adierkens** [player-ui/player#450]
Debugging an issue with assets missing from the registry, and the `fuse` search is obfuscating the real error message
![CleanShot 2024-07-25 at 20 47 17](https://github.com/user-attachments/assets/91aa5dc2-f15a-4aa5-a641-ed2371833332)

![CleanShot 2024-07-25 at 20 47 23](https://github.com/user-attachments/assets/9043be48-df18-4b93-a3c4-d425ba2d1bcc)

**Comment by KetanReddy** [comment]
Huh, that's strange. I'm surprised a test didn't catch that.

**Comment by KetanReddy** [comment]
I was also surprised that TypeScript didn't flag that as an issue, but it looks like we don't have the check for that turned on. So we should probably enable [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess)

**Comment by adierkens** [comment]
I was able to determine the root-cause of the original error -- but my guess is that nothing in the registry came up as a similar matching name and it returned `undef`

I also noticed our bundle size grow ~15kb with the introduction of `fuse.js`: 
| https://bundlephobia.com/package/@player-ui/react@0.8.0-next.2 | https://bundlephobia.com/package/@player-ui/react@0.8.0-next.4 | 
| ---- | ---- | 
| ![CleanShot 2024-07-25 at 21 43 18](https://github.com/user-attachments/assets/7a243062-cec0-4016-8f5a-4582b462b167) | ![CleanShot 2024-07-25 at 21 43 45](https://github.com/user-attachments/assets/ed31b1b3-8a79-4def-9b8b-6c15b32782ec) |


I would try to find something smaller to replace it with, put it behind a `DEBUG` flag, or rip it out entirely

**Comment by KetanReddy** [comment]
Maybe fuzzysort? 5kb isn't bad if we do want to support those kind of suggestions but since we don't really have dev/prod bullds it would have to always get included. https://github.com/farzher/fuzzysort

**Comment by adierkens** [comment]
We likely don't need a full search library, something that computes the Levenshtein distance would be enough to make a suggestion: https://www.npmjs.com/package/leven

**Comment by cehan-Chloe** [comment]
@adierkens thanks for capturing this issue! 
Questions:
1. Could you share the asset info when you debugging the asset missing in registry? I'm surprised that typescript check and test cases didn't capture this issue. Will add new test cases for it.
2. How we check the bundle size before merge pr? https://www.npmjs.com/package/fuse.js?activeTab=readme i was checking the fuse.js but it only has unpacked size
Action item:
1. Replace fuse.js to avoid the bundle size increase
2. Add [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess)
3. Add test cases for this scenario
`I was able to determine the root-cause of the original error -- but my guess is that nothing in the registry came up as a similar matching name and it returned undef`

**Comment by cehan-Chloe** [comment]
ok i'm able to reproduce with the test case below and can confirm it's because no similar type/key name in registry fuse search will return undefined... 
````
  const assetDef = {
    asset: {
      id: "bar-id",
      type: "bar",
    },
  } as unknown as AssetType;

  const registry: AssetRegistryType = new Registry([
    [{ type: "foo", key: "foo-key" }, () => <div>foo</div>],
    [{ type: "a", key: "test" }, () => <div>bar</div>],
  ]);
````

**Comment by adierkens** [comment]
@cehan-Chloe You can use bundlephobia to check the canary version of the Player packages on your PR (similar to what was done in https://github.com/player-ui/player/pull/432)
