### ISSUE TITLE
Broken docs links on storybook page 

### ISSUE THREAD

**Issue by adierkens** [player-ui/player#478]
The link to storybook [here](https://player-ui.github.io/latest/#/tools/storybook) points to the wrong URL -- `#/storybook-demo` instead of `/latest/storybook-demo`

**Comment by smriti0710** [comment]
@adierkens Thanks for tagging the issue. I will be picking this up.

**Comment by smriti0710** [comment]
https://github.com/player-ui/player/pull/528/files

**Comment by adierkens** [comment]
Fixed on `next` branch
