### ISSUE TITLE
Ability to nest expressions

### ISSUE THREAD

**Issue by KieranTH** [player-ui/player#492]
**Is your feature request related to a problem? Please describe.**

It would be really nice if we could have the ability to nest expressions in each other. This is especially nice for when dealing with complex JSON structures in the `data` for Player.

An example of this would be:

```
value: "@[merge2Objects({{objA}}, @[parseObjectB({{objB}})]@)]@"
```

Currently that expression fails purely due to what seems like string splitting on the special characters, `@`, `{{}}` and `[]`.

**Describe the solution you'd like**

For the string splitting logic to be aware of possible nested occurrences of special characters, and to deal with them appropriately. It should probably work "backwards" - Where the deepest expression is ran first, so that the returned instance of that expression can be fed into the parent expression - Unless the expression parser itself can deal with this is in the translation layer.

Cheers!

**Comment by adierkens** [comment]
Hey @KieranTH 

This should actually be supported today (a good push for us to update the docs to make this clearer) 


Once you're inside of an expression block (the contents wrapped by `@[`  `]@`), you're free to use and nest any number of expression calls. In your example, it would be something like:

```
value: "@[ merge2Objects({{objA}}, parseObjectB({{objB}})) ]@"
```

**Comment by kierancap** [comment]
> Hey @KieranTH
> 
> This should actually be supported today (a good push for us to update the docs to make this clearer)
> 
> Once you're inside of an expression block (the contents wrapped by `@[` `]@`), you're free to use and nest any number of expression calls. In your example, it would be something like:
> 
> ```
> value: "@[ merge2Objects({{objA}}, parseObjectB({{objB}})) ]@"
> ```

That's amazing!

Feel free to close this issue in that case :smile: 

Great way of solving the issue too without having to repeat `@[]@` instances!

Thanks

**Comment by KieranTH** [comment]
> Hey @KieranTH
> 
> This should actually be supported today (a good push for us to update the docs to make this clearer)
> 
> Once you're inside of an expression block (the contents wrapped by `@[` `]@`), you're free to use and nest any number of expression calls. In your example, it would be something like:
> 
> ```
> value: "@[ merge2Objects({{objA}}, parseObjectB({{objB}})) ]@"
> ```

That's amazing!

Feel free to close this issue in that case 😄

Great way of solving the issue too without having to repeat @[]@ instances!

Thanks
