### ISSUE TITLE
404 on https://player-ui.github.io/latest/#/storybook-demo

### ISSUE THREAD

**Issue by mlewand100** [player-ui/player#527]
**Describe the bug**
404 error

**To Reproduce**
go to https://player-ui.github.io/latest/#/tools/storybook
select the "here" link in "Reference Assets"

**Expected behavior**

**Screenshots**

**Environment:**

**Additional context**

**Comment by KetanReddy** [comment]
This should be fixed with the doc site rewrite merged with #506 and is available on the next version of the doc site at https://player-ui.github.io/next/. Will close this once this available on the mainline doc site
