### ISSUE TITLE
Comparing diffs between two prereleases is difficult

### ISSUE THREAD

**Issue by sugarmanz** [player-ui/player#549]
**Is your feature request related to a problem? Please describe.**

There is a fix we're looking to consume that has not yet been released yet:
https://github.com/player-ui/player/pull/533

We're a few next releases behind, and need to understand the other impacts of upgrading to the next release containing the above fix. 

The release for that PR when merged, [failed](https://app.circleci.com/pipelines/github/player-ui/player/3483/workflows/6ece90e8-a836-4d2d-9d10-ad5b2248c166?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) -- so it was released on the next PR merged, [0.10.0-next.5](https://github.com/player-ui/player/releases/tag/0.10.0-next.5). As you can see, the release notes for that don't even include the bug fix we want to consume.

**Describe the solution you'd like**

Ideally, prerelease release notes should contain all the changes since the last actual release.

We were also using GH to look at the commits that went in between the two tags:
https://github.com/player-ui/player/compare/0.9.2-next.1...0.10.0-next.5

But it's fairly noisy and easy to miss changes that we are trying to understand. I would think enforcing squash commits could also help in the absence of complete prerelease notes.

**Comment by KetanReddy** [comment]
Definitely agreed. Right now we are cleaning up the previous pre-releases from github but we should probably keep those around, at least until an actual release is made.
