### ISSUE TITLE
Fix links in docs

### ISSUE THREAD

**Issue by brocollie08** [player-ui/player#92]
https://player-ui.github.io/latest/assets/transforms

The `cross platform` link at the bottom of the page doesn't work, it should lead to [this](https://ibp-cicd-core.prod1-ibp.a.intuit.com/player/player/latest/index.html#/core/architecture/cross-platform-players) page (internal link)

https://player-ui.github.io/latest/guides/designing-semantic-assets

`Reference Assets` link at the top is incorrect, link to the current reference assets location

**Comment by devXprite** [comment]
Hii @brocollie08 I want to work on this issue.

**Comment by skodamarthi** [comment]
@brocollie08 Raised https://github.com/player-ui/player/pull/99 to fix this. Can you please check?

**Comment by shubh1646** [comment]
is this issue still open ?
